### PR TITLE
Post Spectra Images Code

### PR DESCRIPTION
**Pull request by SourinDeyUW**
The main experiment program calls the function new_plot_LIG to create images during experiment.

### CODE REVIEW

**Review by hududed — COMMENTED** [review]
@SourinDeyUW
Get rid of unused comments e.g. # In[7]:, d1=pd.read_csv(fn1)
get rid of unused imports e.g. import mplcursors, from sklearn import preprocessing
Use autopep8 format (default CTRL+ALT+F in VSCode) to get rid of whitespaces
remove redundant terms e.g. d1=d1, d1_=_d1, also rename d1_ to _d1

**Review by SourinDeyUW — COMMENTED** [review]
Removed redundant lines

**Review by hududed — COMMENTED** [review]
there are still unused imports e.g. MultipleLocator, mplcursors

**Review by SourinDeyUW — COMMENTED** [review]
removed unused imports

**Review by SourinDeyUW — COMMENTED** [review]
removed unused imports

**Review by SourinDeyUW — COMMENTED** [review]
removed unused imports

**Review by hududed — APPROVED** [review]

**Pull request merged**
